### ISSUE TITLE
Back button doesn't exit app

### ISSUE THREAD

**Issue by dhammel** [simple-login/Simple-Login-Android#6]
Im using version 1.4-fdroid on a pixel 4 non-xl android 10.

The back button pressed once opens side menu, and subsequent presses does nothing. To"exit" you need to press home, though app still runs in background. Needs force close to fully exit.

Small issue, but would be nice to see addressed.

Thank you :)

**Comment by ntnhon** [comment]
Hi @dhammel, thank you for the request. The issue is fixed with [this commit](https://github.com/simple-login/Simple-Login-Android/commit/b3c9009128fb4ad3440a90977d4487934de5b4c0). This will be shipped with some other improvements.

Feel free to open any new issue if you found one that is worth considering (even a minor like this one).

**Comment by dhammel** [comment]
I just got around to compiling the app and installed the self-compiled apk and come to see that this issue still persist as back button doesnt register anything other than opening side menu.

**Comment by ntnhon** [comment]
Maybe because you compile on the master? I didn't merge the fix into master, please refer to "development" branch.

**Comment by dhammel** [comment]
Ok, its working under development branch. Thank you

**Comment by thebrowser** [comment]
Hi, I just downloaded the app from FDroid and I'm having the same issue (pressing the back button does nothing).

App version: SimpleLogin v1.4-fdroid
Running on /e/OS (Android 9)
Phone model Fairphone 3

Wasn't sure if I should open a new issue, please let me know if so and other information you need. Thanks, cheers!

**Comment by ntnhon** [comment]
@thebrowser Hi, I fixed this issue but haven't yet published on neither Play Store nor F-droid. I'm working on the iOS version and will come back later to this app.

If you have Android Studio on your computer, feel free to download the source code (on development branch) and compile it yourself.

**Comment by thebrowser** [comment]
Thanks for the update, I'll try that :+1:

**Comment by ntnhon** [comment]
@thebrowser You're welcome.

If you'd like to install the F-droid version, make sure to chose it properly in the build variants list.
<img width="487" alt="Screen Shot 2020-11-15 at 18 09 42" src="https://user-images.githubusercontent.com/4153453/99191604-f5947d80-276d-11eb-9fb3-f838b4132935.png">
